# Auto-generated by emit_fastlane.py. Do not edit by hand.
# Six-step publish tail — see RECURRING-MISTAKES.md F5.
require 'spaceship'
require 'json'

USERNAME  = "devarafikry@icloud.com"
BUNDLE_ID = "com.devara.splitnow"

Spaceship::ConnectAPI.login(USERNAME, use_portal: false, use_tunes: true)
puts "✓ Login"

app = Spaceship::ConnectAPI::App.find(BUNDLE_ID) or abort("App not found: #{BUNDLE_ID}")

# Discover the unsubmitted version + its latest VALID build.
versions = app.get_app_store_versions(filter: { appStoreState: "PREPARE_FOR_SUBMISSION" })
version  = versions.first or abort("No PREPARE_FOR_SUBMISSION version. Did `deliver` run?")
puts "  version: v#{version.version_string} (#{version.id})"

builds = Spaceship::ConnectAPI::Build.all(app_id: app.id, sort: "-uploadedDate", limit: 5)
build  = builds.find { |b| b.processing_state == "VALID" } or abort("No VALID build yet — retry once processing finishes.")
puts "  build:   v#{build.version} (#{build.id})"

# Resolve appInfo.id (== ageRatingDeclaration.id) for the age rating PATCH.
resp      = Spaceship::ConnectAPI.get_app_infos(app_id: app.id)
app_infos = resp.to_models
app_info  = app_infos.find { |ai| ai.app_store_state == "PREPARE_FOR_SUBMISSION" } || app_infos.first
puts "  appInfo: #{app_info.id} (age rating decl)"

# ── 1. Attach build to version ────────────────────────────────────────────
puts "\n→ Attaching build to version..."
Spaceship::ConnectAPI.patch_app_store_version_with_build(
  app_store_version_id: version.id,
  build_id: build.id,
)
puts "✓ Build attached"

# ── 2. Clear export compliance on the build ───────────────────────────────
puts "\n→ Clearing export compliance (usesNonExemptEncryption=false)..."
Spaceship::ConnectAPI.patch_build(build_id: build.id, attributes: { usesNonExemptEncryption: false }) rescue nil
# Public-API fallback (works even if spaceship's patch_build is unavailable)
puts "  (also via PATCH /v1/builds — see app's API-key-based companion script)"

# ── 3. Age rating (Devara 4+ default — all NONE / false) ──────────────────
puts "\n→ Setting age rating → 4+..."
Spaceship::ConnectAPI.patch_age_rating_declaration(
  age_rating_declaration_id: app_info.id,
  attributes: {
    "alcoholTobaccoOrDrugUseOrReferences" => "NONE",
    "contests"                            => "NONE",
    "gamblingSimulated"                   => "NONE",
    "gunsOrOtherWeapons"                  => "NONE",
    "horrorOrFearThemes"                  => "NONE",
    "matureOrSuggestiveThemes"            => "NONE",
    "medicalOrTreatmentInformation"       => "NONE",
    "profanityOrCrudeHumor"               => "NONE",
    "sexualContentGraphicAndNudity"       => "NONE",
    "sexualContentOrNudity"               => "NONE",
    "violenceCartoonOrFantasy"            => "NONE",
    "violenceRealisticProlongedGraphicOrSadistic" => "NONE",
    "violenceRealistic"                   => "NONE",
    "advertising"            => false,
    "ageAssurance"           => false,
    "gambling"               => false,
    "healthOrWellnessTopics" => false,
    "lootBox"                => false,
    "messagingAndChat"       => false,
    "parentalControls"       => false,
    "unrestrictedWebAccess"  => false,
    "userGeneratedContent"   => false,
  },
)
puts "✓ Age rating set"

# ── 4. Privacy nutrition labels — read from app_privacy_details.json ─────
puts "\n→ Privacy nutrition labels..."
priv_json = File.expand_path("metadata/app_privacy_details.json", __dir__)
usages    = JSON.parse(File.read(priv_json))

Spaceship::ConnectAPI::AppDataUsage.all(app_id: app.id, includes: "category,grouping,purpose,dataProtection", limit: 500).each(&:delete!)
usages.each do |u|
  purposes    = u["purposes"]    || [nil]
  protections = u["data_protections"] || []
  purposes.each do |purpose|
    protections.each do |protection|
      Spaceship::ConnectAPI::AppDataUsage.create(
        app_id: app.id,
        app_data_usage_category_id:   u["category"],
        app_data_usage_protection_id: protection,
        app_data_usage_purpose_id:    purpose,
      )
    end
  end
end
state = Spaceship::ConnectAPI::AppDataUsagesPublishState.get(app_id: app.id)
state.publish! unless state.published
puts "✓ Privacy published"

# ── 5. Create reviewSubmission + add the version + submit ─────────────────
puts "\n→ Creating reviewSubmission..."
submission = app.get_ready_review_submission(platform: "IOS", includes: "items") ||
             app.get_in_progress_review_submission(platform: "IOS", includes: "items")
unless submission
  submission = Spaceship::ConnectAPI.post_review_submission(app_id: app.id, platform: "IOS").to_models.first
end
puts "  submission #{submission.id} state=#{submission.state}"

if (submission.items || []).empty?
  submission.add_app_store_version_to_review_items(app_store_version_id: version.id)
  puts "✓ Added version to review items"
end

if submission.state.nil? || submission.state == "READY_FOR_REVIEW"
  result = submission.submit_for_review
  puts "✓ SUBMITTED — state=#{result.state}"
else
  puts "ℹ Already submitted, state=#{submission.state}"
end
