"""Auto-generated by emit_fastlane.py. Do not edit by hand."""
import json, time, urllib.request, urllib.error
from pathlib import Path
import jwt

KEY_ID    = 'PHT8L76VY9'
ISSUER_ID = "5a94d091-1516-4273-8e07-25e09b16292c"  # Devara studio
APP_ID    = '6771476650'
P8_PATH   = Path.home() / f".appstoreconnect/private_keys/AuthKey_{KEY_ID}.p8"


def _tok():
    now = int(time.time())
    return jwt.encode(
        {"iss": ISSUER_ID, "iat": now, "exp": now + 1200, "aud": "appstoreconnect-v1"},
        P8_PATH.read_text(), algorithm="ES256",
        headers={"kid": KEY_ID, "typ": "JWT"},
    )


def _req(method, path, body=None, t=None):
    r = urllib.request.Request(
        f"https://api.appstoreconnect.apple.com{path}",
        data=json.dumps(body).encode() if body else None,
        method=method,
        headers={"Authorization": f"Bearer {t}", "Content-Type": "application/json"},
    )
    try:
        with urllib.request.urlopen(r) as resp:
            raw = resp.read().decode()
            return json.loads(raw) if raw else {}
    except urllib.error.HTTPError as e:
        print(f"HTTP {e.code}: {e.read().decode()[:600]}")
        return None


def main():
    t = _tok()

    print("→ Setting contentRightsDeclaration...")
    _req("PATCH", f"/v1/apps/{APP_ID}", body={
        "data": {"type": "apps", "id": APP_ID,
                 "attributes": {"contentRightsDeclaration": "DOES_NOT_USE_THIRD_PARTY_CONTENT"}}
    }, t=t)

    print("→ Looking up FREE app price point (USA)...")
    pts = _req("GET", f"/v1/apps/{APP_ID}/appPricePoints?filter[territory]=USA&limit=10", t=t)
    free_id = None
    for p in (pts or {}).get("data", []):
        if float(p["attributes"].get("customerPrice", "x") or 1) == 0.0:
            free_id = p["id"]
            break
    if not free_id:
        print("✗ Could not find FREE price point")
        return 1

    print(f"→ POST appPriceSchedules (FREE, base=USA, point={free_id})...")
    body = {
        "data": {
            "type": "appPriceSchedules",
            "relationships": {
                "app":           {"data": {"type": "apps",        "id": APP_ID}},
                "baseTerritory": {"data": {"type": "territories", "id": "USA"}},
                "manualPrices":  {"data": [{"type": "appPrices",  "id": "${price1}"}]},
            }
        },
        "included": [{
            "type": "appPrices",
            "id": "${price1}",
            "attributes": {"startDate": None},
            "relationships": {
                "appPricePoint": {"data": {"type": "appPricePoints", "id": free_id}}
            }
        }]
    }
    r = _req("POST", "/v1/appPriceSchedules", body=body, t=t)
    if r:
        print(f"✓ Pricing schedule created")


if __name__ == "__main__":
    raise SystemExit(main() or 0)
